openapi: 3.0.3
info:
  title: Clientes API
  description: |-
    API do microsserviço de Clientes
  version: 0.0.1
paths:
  /api/admin/accounts:
    get:
      summary: List accounts
      description: List all accounts
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
    post:
      summary: Add account
      description: Add new account
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        '401':
          description: unauthorized
  /api/admin/accounts/{id}:
    get:
      summary: Find account
      description: Find one specific account
      parameters:
        - name: id
          in: path
          description: ID of account that needs to be fetched
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Account"
        '400':
          description: invalid ID supplied
        '404':
          description: not found
    put:
      summary: Update account
      description: Update account by entering the whole updated account
      parameters:
      - name: id
        in: path
        description: ID of account that needs to be updated
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/Account"
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Account"
        '400':
          description: invalid ID supplied
        '401':
          description: unauthorized
    delete:
      summary: Delete account
      description: Delete account by entering its ID
      parameters:
      - name: id
        in: path
        description: ID of account that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        '204':
          description: no content
        '401':
          description: unauthorized
        '400':
          description: invalid ID supplied
  /api/admin/transactions:
    post:
      summary: Create transaction
      description: Create a new transaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedTransaction'
        '422':
          description: transactionvalidation error
          content:
            application/json:
              example: 'Validation Error'
        '400':
          description: error
          content:
            application/json:
              example: 'Error'
  /api/admin/transactions/{id}:
    parameters:
    - name: id
      in: path
      description: Transaction ID
      required: true
      schema:
        type: string
    get:
      summary: Get transaction by ID
      description: Get a transaction by its ID
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedTransaction'
        '404':
          description: not found
          content:
            application/json:
              schema:
                example: 'Not Found'
    put:
      summary: Update transaction by ID
      description: Update a transaction by its ID if its status is 'under analysis'
      responses:
        '204':
          description: updated
        '404':
          description: not found
          content:
            application/json:
              schema:
                example: 'Not Found'
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        email:
          type: string
          format: email
        senha:
          type: string
          format: password
    Transaction:
      type: object
      properties:
        valor:
          type: number
          format: decimal
        idCliente:
          type: string
        status:
          type: string
          enum: ['Aprovada', 'Em análise', 'Reprovada']
    CreatedTransaction:
      type: object
      properties:
        id:
          type: string
        valor:
          type: number
        idCliente:
          type: number
        status:
          type: string
          enum: ['Aprovada', 'Em análise', 'Reprovada']